# meccha:init/build_registry
# Guarded one-shot. Invokes every generated builder emitted by the
# Pillar-2 Python pipeline, then stamps the loaded flag so this whole
# chain is skipped on subsequent /reload calls.
#
# NOTE: meccha:generated/_index is itself regenerated by the Python tool
# (tools/parse_assets.py). It simply `function`-calls every emitted file
# in dependency order: textures -> states -> shapes -> vertices.

say [Meccha] First-time registry build - loading relational asset data...

function meccha:generated/_index

# Stamp version + loaded flag last, so a crash mid-build re-runs cleanly.
data modify storage meccha:registry meta set value {loaded:1b, version:1, scale:1000}

say [Meccha] Registry build complete.
